const fs = require('node:fs')

const required = [
  'package.json',
  'electron.vite.config.js',
  'src/main/index.js',
  'src/preload/index.js',
  'src/renderer/src/App.vue',
  'database/schema.sql',
  'database/cafetal-os-demo.db',
  'database/demo_seeds.sql',
  'scripts/create_empty_database.js',
  'scripts/check-electron.js',
  'scripts/clean-generated.js',
  'scripts/ensure-electron.sh',
  'scripts/windows/ensure-electron.bat',
  'docs/DESARROLLO.md',
  'docs/RESPONSIVE_Y_MOVIL.md',
  'docs/IDENTIDAD_VISUAL.md',
  'docs/decisions/README.md',
  'branding/cafetal-os-logo-original.png',
  'branding/cafetal-os-logo-clean.png',
  'branding/cafetal-os-app-icon.png',
  'IMG/referencias/lotes-v2.0.png',
  'IMG/referencias/beneficio-v2.0.png',
  'COMMUNITY.md',
  'GOVERNANCE.md',
  'SUPPORT.md',
  'CITATION.cff',
  'scripts/verify-bundle.js',
  'src/main/auth-store.js',
  'src/renderer/src/views/LoginView.vue',
  'src/renderer/src/views/SettingsView.vue',
  'docs/AUTENTICACION_USUARIOS.md',
  'docs/CONFIGURACION_Y_DEMO.md',
  'docs/NAVEGACION_Y_UX.md',
  'docs/CAPTURAS_PLAYWRIGHT.md',
  'IMG/README.md',
  'tests/e2e/screenshots.spec.js',
  'capturar-pantallas.bat',
  'README.md',
  'SECURITY.md',
  'CHANGELOG.md',
  'docs/MANUAL_USUARIO.md',
  'tests/unit/navigation.spec.js',
  'tests/unit/demo-integrity.spec.js',
  'tests/unit/mobile-drawer.spec.js',
  'scripts/windows/run-demo.bat',
  'src/main/mcp-server.js',
  'src/main/domain-validation.js',
  'src/main/weather-service.js',
  'src/renderer/src/components/McpSettingsPanel.vue',
  'src/renderer/src/components/ReportSettingsPanel.vue',
  'docs/MCP_IA_LOCAL.md',
  'docs/VALIDACIONES_INTELIGENTES.md',
  'docs/REPORTES_MEMBRETE.md',
  'docs/PUBLICAR_RELEASE_GITHUB.md',
  'mcp/README.md',
  'mcp/clients/generic-readonly.example.json',
  'mcp/clients/generic-demo.example.json',
  'scripts/run-mcp.cjs',
  'scripts/mcp-smoke-test.cjs',
  'scripts/windows/run-mcp.bat',
  'mcp.bat',
  'mcp-demo.bat',
  'publicar-release.bat',
  'tests/unit/domain-validation.spec.js',
  'tests/unit/mcp-server.spec.js',
  'tests/unit/report-branding.spec.js',
  'src/renderer/src/components/OperationSettingsPanel.vue',
  'src/renderer/public/legacy/registro-masivo.js',
  'src/renderer/public/legacy/compras.js',
  'docs/PLANILLAS_CORTE.md',
  'docs/REGISTRO_MASIVO.md',
  'docs/COMPRAS_ACOPIO.md',
  'docs/EDUCACION_INTERACTIVA.md',
  'docs/RELEASE_NOTES_2.6.0.md',
  'docs/CLIMA_OPEN_METEO.md',
  'docs/VENTAS_KARDEX_Y_ALMACENAMIENTO.md',
  'src/renderer/public/legacy/ventas.js',
  'tests/unit/bulk-workflows.spec.js',
  'tests/unit/education-help.spec.js',
  'tests/unit/weather-service.spec.js',
]

const missing = required.filter((file) => !fs.existsSync(file))

if (missing.length) {
  console.error(`Faltan archivos esenciales:\n${missing.map((file) => ` - ${file}`).join('\n')}`)
  process.exit(1)
}

console.log(`Proyecto verificado: ${required.length} archivos esenciales presentes.`)
